name: Build RustDesk

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: 下载源代码和子模块
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: 安装 Rust (官方方法)
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        
    - name: 安装编译工具
      run: |
        choco install -y nasm yasm
        
    - name: 编译 RustDesk
      run: |
        cargo build --release --bin rustdesk
        mkdir release
        copy target\release\rustdesk.exe release\
        
    - name: 上传编译结果
      uses: actions/upload-artifact@v4
      with:
        name: rustdesk-windows
        path: release/

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: 下载源代码和子模块
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: 安装 Rust (官方方法)
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        
    - name: 安装 Linux 依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ gcc git curl wget nasm yasm \
          libgtk-3-dev clang libxcb-randr0-dev \
          libxdo-dev libxfixes-dev libxcb-shape0-dev \
          libxcb-xfixes0-dev libasound2-dev libpulse-dev \
          cmake pkg-config
        
    - name: 编译 RustDesk
      run: |
        cargo build --release --bin rustdesk
        mkdir -p release
        cp target/release/rustdesk release/
        
    - name: 上传编译结果
      uses: actions/upload-artifact@v4
      with:
        name: rustdesk-linux
        path: release/
