name: Build RustDesk Fixed

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: 下载源代码和子模块
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: 安装 Rust
      run: |
        curl -sSf -o rustup-init.exe https://win.rustup.rs/x86_64
        .\rustup-init.exe -y --default-toolchain stable
        echo "C:\Users\runneradmin\.cargo\bin" >> $env:GITHUB_PATH

    - name: 安装 Visual Studio Build Tools
      run: |
        choco install -y visualstudio2019buildtools
        choco install -y nasm yasm

    - name: 设置构建环境
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

    - name: 编译 RustDesk
      run: |
        cargo build --release --bin rustdesk

    - name: 上传 Windows 版本
      uses: actions/upload-artifact@v4
      with:
        name: rustdesk-windows
        path: target/release/rustdesk.exe
