name: Build RustDesk with VCPKG

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: 检出代码和子模块
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: 安装 Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1.3
      
    - name: 安装 Rust
      run: |
        curl -sSf -o rustup-init.exe https://win.rustup.rs/x86_64
        .\rustup-init.exe -y --default-toolchain stable
        echo "C:\Users\runneradmin\.cargo\bin" >> $env:GITHUB_PATH

    - name: 安装构建工具
      run: |
        choco install -y nasm yasm cmake git

    - name: 安装和配置 vcpkg
      run: |
        # 安装 vcpkg
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg integrate install
        
        # 安装 magnum-opus 需要的依赖
        .\vcpkg install opus:x64-windows
        .\vcpkg install libvpx:x64-windows
        .\vcpkg install ffmpeg:x64-windows
        
        # 设置环境变量
        echo "VCPKG_ROOT=$pwd" >> $env:GITHUB_ENV
        echo "VCPKGRS_DYNAMIC=1" >> $env:GITHUB_ENV

    - name: 验证 vcpkg 安装
      run: |
        echo "VCPKG_ROOT: $env:VCPKG_ROOT"
        cd $env:VCPKG_ROOT
        .\vcpkg list

    - name: 编译 RustDesk
      run: |
        cargo build --release --bin rustdesk

    - name: 上传编译结果
      uses: actions/upload-artifact@v4
      with:
        name: rustdesk-windows-vcpkg
        path: target/release/rustdesk.exe
