name: Debug Build Issues

on:
  workflow_dispatch:

jobs:
  diagnose:
    runs-on: windows-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: 显示系统信息
      run: |
        echo "系统信息:"
        systeminfo | select-string "OS Name","OS Version"
        echo "磁盘信息:"
        Get-PSDrive -PSProvider FileSystem
        echo "环境变量:"
        echo "PATH=$env:PATH"
        echo "RUSTUP_HOME=$env:RUSTUP_HOME"
        echo "CARGO_HOME=$env:CARGO_HOME"
        
    - name: 检查 Rust 工具链
      run: |
        rustc --version
        cargo --version
        rustup toolchain list
        rustup target list | findstr windows
        
    - name: 检查依赖状态
      run: |
        echo "检查子模块:"
        git submodule status
        echo "检查 Cargo.toml:"
        type Cargo.toml | findstr magnum-opus || echo "magnum-opus 未在根 Cargo.toml 中找到"
        
    - name: 检查 vcpkg 相关配置
      run: |
        echo "检查 vcpkg 环境:"
        echo "VCPKG_ROOT=$env:VCPKG_ROOT"
        echo "检查是否安装了 vcpkg:"
        where vcpkg || echo "vcpkg 未安装"
        
    - name: 尝试编译单个库
      run: |
        echo "尝试编译 hbb_common..."
        cargo build -p hbb_common --release || echo "hbb_common 编译失败"
        
        echo "尝试编译 magnum-opus..."
        cargo build -p magnum-opus --release || echo "magnum-opus 编译失败，这是问题所在"
        
    - name: 上传诊断信息
      uses: actions/upload-artifact@v4
      with:
        name: build-diagnostics
        path: |
          Cargo.toml
          Cargo.lock
