name: Download and Customize RustDesk

on:
  workflow_dispatch:

jobs:
  download-windows:
    runs-on: windows-latest
    
    steps:
    - name: 下载官方 RustDesk Windows 版本
      run: |
        # 下载最新版本的 RustDesk
        curl -L -o rustdesk.zip https://github.com/rustdesk/rustdesk/releases/download/1.2.3/rustdesk-1.2.3-x86_64.exe.zip
        Expand-Archive rustdesk.zip -Force
        dir
        
    - name: 创建自定义配置文件
      run: |
        # 创建 RustDesk 配置文件
        $configContent = @"
        [options]
        key = your-custom-key
        relay-server = your-relay-server.com:21117
        api-server = your-api-server.com:21114
        encrypted-only = 1
        "@
        
        # 将配置写入文件（RustDesk 启动时会读取）
        Set-Content -Path "rustdesk-config.toml" -Value $configContent
        
    - name: 创建安装脚本
      run: |
        # 创建批处理文件来自动配置
        $batchContent = @"
        @echo off
        echo 正在配置 RustDesk...
        copy rustdesk-config.toml %USERPROFILE%\.rustdesk\config.toml
        echo 配置完成！
        rustdesk.exe
        "@
        
        Set-Content -Path "setup-rustdesk.bat" -Value $batchContent

    - name: 打包自定义版本
      run: |
        # 创建包含可执行文件和配置的zip文件
        Compress-Archive -Path rustdesk.exe, rustdesk-config.toml, setup-rustdesk.bat -DestinationPath rustdesk-custom.zip

    - name: 上传自定义版本
      uses: actions/upload-artifact@v4
      with:
        name: rustdesk-custom-windows
        path: rustdesk-custom.zip
