name: Build RustDesk Alternative Deps

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: 修改 Cargo.toml 使用替代依赖
      run: |
        # 备份 Cargo.toml
        Copy-Item Cargo.toml Cargo.toml.backup
        
        # 创建一个不使用 magnum-opus 的补丁版本
        (Get-Content Cargo.toml) -replace 'magnum-opus = .*', '# magnum-opus = { git = "https://github.com/rustdesk-org/magnum-opus" }' | Set-Content Cargo.toml
        
        # 添加替代的音频库
        @"
        [patch.'https://github.com/rustdesk-org/magnum-opus']
        magnum-opus = { git = 'https://github.com/rustdesk/rustdesk', branch = 'master' }
        "@ >> Cargo.toml

    - name: 安装 Rust
      run: |
        curl -sSf -o rustup-init.exe https://win.rustup.rs/x86_64
        .\rustup-init.exe -y --default-toolchain stable
        echo "C:\Users\runneradmin\.cargo\bin" >> $env:GITHUB_PATH

    - name: 安装构建工具
      run: |
        choco install -y nasm yasm

    - name: 更新依赖
      run: |
        cargo update

    - name: 编译 RustDesk
      run: |
        cargo build --release --bin rustdesk

    - name: 上传编译结果
      uses: actions/upload-artifact@v4
      with:
        name: rustdesk-windows-alternative
        path: target/release/rustdesk.exe
